/*
   This file has been generated by IDA Pro.
   It contains local type definitions from
     F:\Games\CIV3\Civilization III\Conquests\Civ3Conquests.idb
*/

/*   23 */
#pragma pack(push, 1)
struct struct_String32
{
  char S[32];
};
#pragma pack(pop)

/*   24 */
#pragma pack(push, 1)
struct struct_String24
{
  char S[24];
};
#pragma pack(pop)

/*   25 */
#pragma pack(push, 1)
struct struct_String16
{
  char field_0[16];
};
#pragma pack(pop)

/*   67 */
#pragma pack(push, 1)
struct struct_String64
{
  char S[64];
};
#pragma pack(pop)

/*   80 */
#pragma pack(push, 1)
struct struct_String260
{
  char S[260];
};
#pragma pack(pop)

/*  139 */
#pragma pack(push, 1)
struct struct_String264
{
  char S[264];
};
#pragma pack(pop)

/*  141 */
#pragma pack(push, 1)
struct struct_String256
{
  char S[256];
};
#pragma pack(pop)


/* End of file */
